# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bf4266bc264ea3adfaaa793f2d371dbc00b235292d78af9949554bd1e32ac812dacb3172a62e0075cfad4b5a173f01b36b9917cd9a6e24ede63079ddbd816d0

test:
  secret_key_base: 967893f428839d399e804c13a5455513272e30bd101de4ed5387167f3e4f3c339584ad5efd3300c56e3fd7455bdf827fba305ba8fd0eb2c257889451f6637dcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
